kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp mkteileX-suffix=HTFlmkteileX/suffix=HTFmkteileX-suffi
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp úúúúõDOúúúë€ÿÿÿÿÿÿÿÿÿúúÿÿúúúúúúúúúú    €
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp ????????????
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp ??è?'???????????
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp  
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp ð
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp siˆfix=HT	
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp QQQQQQQtile
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp leùeile	*
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp teÿe	*
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp teÿe
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp b
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp îtei|
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp Q
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp b
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp îteib
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp QQ
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp m7FmkR
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp í@ísƒƒvteittyf
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp le
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp ÿ
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp “ÿXE
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp +
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp le
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp þ
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp )õ
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp *
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp î
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 	
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp xÿ|ucï
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp 
kcov --collect-only /root/coverage/ /root/coreutils/src/mktemp öXXXööööÿÿÿööö 
